# Generated by Django 3.2.21 on 2023-09-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('careerpath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdl_careerpaths.careerpath')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdl_careerpaths.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdl_careerpaths.level')),
            ],
        ),
    ]
